In [1]:
import pandas as pd
df = pd.read_csv('D:\IND_prep\data\loans\loans.csv',encoding='utf-8')

In [2]:
df.head()

,total_credit_utilized,installment,grade,state,issue_date,application_time,accounts,vector_feature,non_decimal_feature,sentence_feature,y
0,38767,652.53,C,NJ,16-Apr-18,13:28:43.3,"{""current_delinq"":0,""current_installment"":2,""o...","[3.03, 5.92, 0.95, 7.29, 3.68]",0b11011001,배터리 잔량 부족,0
1,4321,167.54,C,HI,13-Feb-18,10:43:08.5,"{""current_delinq"":0,""current_installment"":0,""o...","[4.1, 1.11, 4.34, 3.13, 6.4]",0b1000110001,센서 값 정상 범위,0
2,16000,71.40,D,WI,23-Mar-18,15:44:08.2,"{""current_delinq"":0,""current_installment"":1,""o...","[8.17, 4.8, 4.53, 9.54, 6.86]",0x2f,정기 점검 완료,0
3,4997,664.19,A,PA,09-Jan-18,11:32:42.6,"{""current_delinq"":0,""current_installment"":1,""o...","[1.83, 4.44, 5.1, 7.02, 6.71]",0x124,모터 온도 상승 경고,0
4,52722,786.87,C,CA,08-Apr-18,10:33:13.3,"{""current_delinq"":0,""current_installment"":1,""o...","[2.54, 6.9, 5.92, 1.53, 7.17]",0xe0,정기 점검 완료,0

In [3]:

# 새로운 영어 컬럼명 정의
new_english_column_names = {
    'grade': 'efficiency_rating',
    'state': 'operating_status',
    'accounts': 'equipment_id'
}

# 컬럼명 변경
df.rename(columns=new_english_column_names, inplace=True)
print("\n영어 컬럼명으로 변경 후:")
df.head()

영어 컬럼명으로 변경 후:

,total_credit_utilized,installment,efficiency_rating,operating_status,issue_date,application_time,equipment_id,vector_feature,non_decimal_feature,sentence_feature,y
0,38767,652.53,C,NJ,16-Apr-18,13:28:43.3,"{""current_delinq"":0,""current_installment"":2,""o...","[3.03, 5.92, 0.95, 7.29, 3.68]",0b11011001,배터리 잔량 부족,0
1,4321,167.54,C,HI,13-Feb-18,10:43:08.5,"{""current_delinq"":0,""current_installment"":0,""o...","[4.1, 1.11, 4.34, 3.13, 6.4]",0b1000110001,센서 값 정상 범위,0
2,16000,71.40,D,WI,23-Mar-18,15:44:08.2,"{""current_delinq"":0,""current_installment"":1,""o...","[8.17, 4.8, 4.53, 9.54, 6.86]",0x2f,정기 점검 완료,0
3,4997,664.19,A,PA,09-Jan-18,11:32:42.6,"{""current_delinq"":0,""current_installment"":1,""o...","[1.83, 4.44, 5.1, 7.02, 6.71]",0x124,모터 온도 상승 경고,0
4,52722,786.87,C,CA,08-Apr-18,10:33:13.3,"{""current_delinq"":0,""current_installment"":1,""o...","[2.54, 6.9, 5.92, 1.53, 7.17]",0xe0,정기 점검 완료,0

In [4]:
df[df.columns[3]].unique()

array(['NJ', 'HI', 'WI', 'PA', 'CA', 'KY', 'MI', 'AZ', 'NV', 'IL', 'FL',
       'SC', 'CO', 'TN', 'TX', 'VA', 'NY', 'GA', 'MO', 'AR', 'MD', 'NC',
       'NE', 'WV', 'NH', 'UT', 'DE', 'MA', 'OR', 'OH', 'OK', 'SD', 'MN',
       'AL', 'WY', 'LA', 'IN', 'KS', 'MS', 'WA', 'ME', 'VT', 'CT', 'NM',
       'AK', 'MT', 'RI', 'ND', 'DC', 'ID'], dtype=object)

In [5]:
df[df.columns[6]].unique()

array(['{"current_delinq":0,"current_installment":2,"opened_24m":5,"satisfactory":10,"120d_past_due":0,"30d_past_due":0,"active_debit":2,"total_cc":14,"open_cc":8,"mort":1}',
       '{"current_delinq":0,"current_installment":0,"opened_24m":11,"satisfactory":14,"120d_past_due":0,"30d_past_due":0,"active_debit":3,"total_cc":24,"open_cc":14,"mort":0}',
       '{"current_delinq":0,"current_installment":1,"opened_24m":13,"satisfactory":10,"120d_past_due":0,"30d_past_due":0,"active_debit":3,"total_cc":14,"open_cc":8,"mort":0}',
       ...,
       '{"current_delinq":0,"current_installment":3,"opened_24m":4,"satisfactory":11,"120d_past_due":0,"30d_past_due":0,"active_debit":5,"total_cc":9,"open_cc":7,"mort":2}',
       '{"current_delinq":0,"current_installment":2,"opened_24m":2,"satisfactory":15,"120d_past_due":0,"30d_past_due":0,"active_debit":1,"total_cc":15,"open_cc":9,"mort":6}',
       '{"current_delinq":0,"current_installment":5,"opened_24m":4,"satisfactory":11,"120d_past_due":0,"30d_past_due":0,"active_debit":5,"total_cc":6,"open_cc":5,"mort":0}'],
      shape=(9498,), dtype=object)

In [6]:
import json
# 1. operating_status의 원본 데이터를 삭제하고, 새로운 값들로 변경
# 정의된 새로운 operating_status 값들 (10개)
defined_operating_statuses = [
    'Commissioning',        # 시운전
    'Decommissioning',      # 사용중지/폐기절차
    'Emergency_Shutdown',   # 비상정지
    'Fault_Condition',      # 오류상태
    'Restart_Sequence',     # 재가동절차
    'Scheduled_Outage',     # 계획정지
    'Load_Ramping',         # 부하증감발
    'Peak_Operation',       # 최대부하운전
    'Bypass_Active',        # 우회운전
    'Remote_Monitoring'     # 원격감시
]


# 기존 DataFrame의 길이에 맞춰 새로운 상태값을 할당 (순환 사용)
num_rows = len(df)
df['operating_status'] = [defined_operating_statuses[i % len(defined_operating_statuses)] for i in range(num_rows)]

print("\noperating_status를 새로운 값으로 변경 후 고유값:")
print(df['operating_status'].unique())

operating_status를 새로운 값으로 변경 후 고유값:
['Commissioning' 'Decommissioning' 'Emergency_Shutdown' 'Fault_Condition'
 'Restart_Sequence' 'Scheduled_Outage' 'Load_Ramping' 'Peak_Operation'
 'Bypass_Active' 'Remote_Monitoring']

array(['{"current_delinq":0,"current_installment":2,"opened_24m":5,"satisfactory":10,"120d_past_due":0,"30d_past_due":0,"active_debit":2,"total_cc":14,"open_cc":8,"mort":1}',
       '{"current_delinq":0,"current_installment":0,"opened_24m":11,"satisfactory":14,"120d_past_due":0,"30d_past_due":0,"active_debit":3,"total_cc":24,"open_cc":14,"mort":0}',
       '{"current_delinq":0,"current_installment":1,"opened_24m":13,"satisfactory":10,"120d_past_due":0,"30d_past_due":0,"active_debit":3,"total_cc":14,"open_cc":8,"mort":0}',
       ...,
       '{"current_delinq":0,"current_installment":3,"opened_24m":4,"satisfactory":11,"120d_past_due":0,"30d_past_due":0,"active_debit":5,"total_cc":9,"open_cc":7,"mort":2}',
       '{"current_delinq":0,"current_installment":2,"opened_24m":2,"satisfactory":15,"120d_past_due":0,"30d_past_due":0,"active_debit":1,"total_cc":15,"open_cc":9,"mort":6}',
       '{"current_delinq":0,"current_installment":5,"opened_24m":4,"satisfactory":11,"120d_past_due":0,"30d_past_due":0,"active_debit":5,"total_cc":6,"open_cc":5,"mort":0}'],
      shape=(9498,), dtype=object)

In [7]:
# 2. equipment_id JSON 데이터의 키값 변경
# 키 매핑 정의 (기존 키: 새 키)
key_mapping = {
    "current_delinq": "asset_tag",
    "current_installment": "equipment_category",
    "opened_24m": "location_id",
    "satisfactory": "capacity_rating",
    "120d_past_due": "criticality_level",
    "30d_past_due": "expected_lifespan_years",
    "active_debit": "max_operating_pressure_bar",
    "total_cc": "operating_hours_total",
    "open_cc": "resting_hours_total",
    "mort": "purchase_cost",
}

def rename_json_keys(json_string, mapping):
    if pd.isna(json_string):
        return json_string
    try:
        data_dict = json.loads(json_string)
        new_dict = {}
        for old_key, value in data_dict.items():
            new_key = mapping.get(old_key, old_key) # 매핑에 없으면 기존 키 유지
            new_dict[new_key] = value
        return json.dumps(new_dict)
    except json.JSONDecodeError:
        return json_string # 파싱 오류 시 원본 반환

df['equipment_id'] = df['equipment_id'].apply(lambda x: rename_json_keys(x, key_mapping))

print("\n최종 equipment_id (키 변경 후, 첫 번째 행):")
print(df['equipment_id'].iloc[0])

최종 equipment_id (키 변경 후, 첫 번째 행):
{"asset_tag": 0, "equipment_category": 2, "location_id": 5, "capacity_rating": 10, "criticality_level": 0, "expected_lifespan_years": 0, "max_operating_pressure_bar": 2, "operating_hours_total": 14, "resting_hours_total": 8, "purchase_cost": 1}

In [8]:
df.head()

,total_credit_utilized,installment,efficiency_rating,operating_status,issue_date,application_time,equipment_id,vector_feature,non_decimal_feature,sentence_feature,y
0,38767,652.53,C,Commissioning,16-Apr-18,13:28:43.3,"{""asset_tag"": 0, ""equipment_category"": 2, ""loc...","[3.03, 5.92, 0.95, 7.29, 3.68]",0b11011001,배터리 잔량 부족,0
1,4321,167.54,C,Decommissioning,13-Feb-18,10:43:08.5,"{""asset_tag"": 0, ""equipment_category"": 0, ""loc...","[4.1, 1.11, 4.34, 3.13, 6.4]",0b1000110001,센서 값 정상 범위,0
2,16000,71.40,D,Emergency_Shutdown,23-Mar-18,15:44:08.2,"{""asset_tag"": 0, ""equipment_category"": 1, ""loc...","[8.17, 4.8, 4.53, 9.54, 6.86]",0x2f,정기 점검 완료,0
3,4997,664.19,A,Fault_Condition,09-Jan-18,11:32:42.6,"{""asset_tag"": 0, ""equipment_category"": 1, ""loc...","[1.83, 4.44, 5.1, 7.02, 6.71]",0x124,모터 온도 상승 경고,0
4,52722,786.87,C,Restart_Sequence,08-Apr-18,10:33:13.3,"{""asset_tag"": 0, ""equipment_category"": 1, ""loc...","[2.54, 6.9, 5.92, 1.53, 7.17]",0xe0,정기 점검 완료,0

In [9]:
# 새로운 산업 특화 컬럼명 정의
industrial_column_names_update = {
    'total_credit_utilized': 'total_primary_resource_consumed',  # 예: 총 연료 소비량(톤), 총 가스 사용량(m³) 등
    'installment': 'current_output_quantity' ,      # 예: 시간당 발전량(MWh), 일일 가스 공급량(m³), 현재 유량 등
    'vector_feature': 'sensor_energy_band',
    'non_decimal_feature': 'sensor_error_flags_binary',
    'sentence_feature': 'facility_status'
}

# 컬럼명 변경
df.rename(columns=industrial_column_names_update, inplace=True)

print("\nDataFrame after renaming columns:")
print(df.head())

DataFrame after renaming columns:
   total_primary_resource_consumed  current_output_quantity efficiency_rating  \
0                            38767                   652.53                 C
1                             4321                   167.54                 C
2                            16000                    71.40                 D
3                             4997                   664.19                 A
4                            52722                   786.87                 C

     operating_status issue_date application_time  \
0       Commissioning  16-Apr-18       13:28:43.3
1     Decommissioning  13-Feb-18       10:43:08.5
2  Emergency_Shutdown  23-Mar-18       15:44:08.2
3     Fault_Condition  09-Jan-18       11:32:42.6
4    Restart_Sequence  08-Apr-18       10:33:13.3

                                        equipment_id  \
0  {"asset_tag": 0, "equipment_category": 2, "loc...
1  {"asset_tag": 0, "equipment_category": 0, "loc...
2  {"asset_tag": 0, "equipment_category": 1, "loc...
3  {"asset_tag": 0, "equipment_category": 1, "loc...
4  {"asset_tag": 0, "equipment_category": 1, "loc...

               sensor_energy_band sensor_error_flags_binary facility_status  y
0  [3.03, 5.92, 0.95, 7.29, 3.68]                0b11011001       배터리 잔량 부족  0
1    [4.1, 1.11, 4.34, 3.13, 6.4]              0b1000110001      센서 값 정상 범위  0
2   [8.17, 4.8, 4.53, 9.54, 6.86]                      0x2f        정기 점검 완료  0
3   [1.83, 4.44, 5.1, 7.02, 6.71]                     0x124     모터 온도 상승 경고  0
4   [2.54, 6.9, 5.92, 1.53, 7.17]                      0xe0        정기 점검 완료  0

In [10]:
df.head()

,total_primary_resource_consumed,current_output_quantity,efficiency_rating,operating_status,issue_date,application_time,equipment_id,sensor_energy_band,sensor_error_flags_binary,facility_status,y
0,38767,652.53,C,Commissioning,16-Apr-18,13:28:43.3,"{""asset_tag"": 0, ""equipment_category"": 2, ""loc...","[3.03, 5.92, 0.95, 7.29, 3.68]",0b11011001,배터리 잔량 부족,0
1,4321,167.54,C,Decommissioning,13-Feb-18,10:43:08.5,"{""asset_tag"": 0, ""equipment_category"": 0, ""loc...","[4.1, 1.11, 4.34, 3.13, 6.4]",0b1000110001,센서 값 정상 범위,0
2,16000,71.40,D,Emergency_Shutdown,23-Mar-18,15:44:08.2,"{""asset_tag"": 0, ""equipment_category"": 1, ""loc...","[8.17, 4.8, 4.53, 9.54, 6.86]",0x2f,정기 점검 완료,0
3,4997,664.19,A,Fault_Condition,09-Jan-18,11:32:42.6,"{""asset_tag"": 0, ""equipment_category"": 1, ""loc...","[1.83, 4.44, 5.1, 7.02, 6.71]",0x124,모터 온도 상승 경고,0
4,52722,786.87,C,Restart_Sequence,08-Apr-18,10:33:13.3,"{""asset_tag"": 0, ""equipment_category"": 1, ""loc...","[2.54, 6.9, 5.92, 1.53, 7.17]",0xe0,정기 점검 완료,0

In [11]:
csv = df.to_csv(r'D:\IND_prep\data\sensor\ind_iot.csv',index=False,encoding='utf-8-sig')

In [12]:
for i in df.columns:
    print(i, end=',')

total_primary_resource_consumed,current_output_quantity,efficiency_rating,operating_status,issue_date,application_time,equipment_id,sensor_energy_band,sensor_error_flags_binary,facility_status,y,